### ISSUE TITLE
--pretty=oneline does not always produce single lines

### ISSUE THREAD

**Issue by stuarthalloway** [Datomic/codeq#1]
Commits can still have linefeeds, if the message is also in a double quoted string. E.g. the rails repository has this commit (note the trailing ^M)

```
e04818d1b8de44d47003031791f142182320ed89 Revert "Make sure :environment task is executed before db:schema:load or db:structure:load^M"
```

The commit above throws off the import and causes 

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 40
```

We need to either parse smarter than with line-seq, or pass a different --pretty flag when reading in commits.

P.S. Not all "Revert" commits have the trailing ^M -- there is no pattern that I have discovered.

**Comment by samumbach** [comment]
^M is carriage return. Perhaps this is something to do with DOS-style CR+LF line endings?
